ops:
  env: dev
  aws_account: "123456789012"
  aws_region: us-east-1
resources:
  s3:
    bucket_name: my-artifact-bucket-dev
    versioned: false
  vpc:
    cidr: 10.2.2.0/25
    max_azs: 2
    nat_gateways: 1
    subnets:
      public:
        enabled: true
        cidr_mask: 27
      private:
        enabled: true
        cidr_mask: 27
      private_isolated:
        enabled: false